<?php
class Error_Type{

	const FORM = "FORM";

	const DATA_BASE = "DATA_BASE";

	const SAME_USER_NAME="SAME_USER_NAME";

	const SAME_CATEGORY_NAME = "SAME CATEGORY NAME";

	const SAME_REGISTERED_DATA = "SAME REGISTERED DATA";

}