<?php
require("../../../../CONFIGURATION/Config.php");
require(DB);
require("../../../../MODEL/User.php");
require("../../../../MODEL/User_Type.php");
require("../../../../CONTROLLER/User_Controller.php");
require("../../../../CONTROLLER/Operator_Controller.php");
require("../SECURE_FOR_OPERATOR.php");
require("../../../../MODEL/GeneralCategory.php");